#!/bin/bash

help() {
    echo "Usage: $0 <server_name>"
    exit 1
}

[[ "$#" -eq 1 && -n "$1" ]] || help

echo "Revoking key for $1."

cd /etc/openvpn/easy-rsa

./revoke-full $1

# Remove entry from ipp.txt then reload
service openvpn stop
sed -i.bak '/^$1/d' /etc/openvpn/ipp.txt
service openvpn start

echo "Certificate revoked."
